services:
  db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank_db
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  goose:
    image: artsafin/goose-migrations
    hostname: goose
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: "postgres postgres://postgres:postgres@postgres:5432/bank_db?sslmode=disable up"


  consumer:
    image: bank_service:latest
    restart: always
    hostname: consumer
    environment:
      - APP_ENV=prod # supported app env "dev"
      - PUB_ENV=prod # supported pub env "dev"
      - PG_URL=postgres://postgres:postgres@postgres:5432/bank_db
      - AMQP_URL=amqp://rmuser:rmpassword@rabbitmq:5672/
      - AMQP_EXCHANGE=transactions-exchange
      - AMQP_QUEUE=transaction-queue
      - AMQP_ROUTING_KEY=transactions-routing-key
      - AMQP_CONSUMER_TAG=transactions-consumer
      - AMQP_WORKER_POOL_SIZE=20
    depends_on:
      - db
      - rabbitmq

  producer:
    image: producer:latest
    restart: always
    hostname: producer
    environment:
      - PRODUCER_ENV=prod # supported app env "dev"
      - AMQP_URL=amqp://rmuser:rmpassword@rabbitmq:5672/
      - AMQP_EXCHANGE=transactions-exchange
      - AMQP_ROUTING_KEY=transactions-routing-key
    depends_on:
      - rabbitmq
      - consumer