services:
  db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank_db
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  app:
    image: bank_service:latest
    restart: always
    hostname: app
    environment:
      - PG_URL=postgres://postgres:postgres@postgres:5432/bank_db
      - AMQP_URL=amqp://rmuser:rmpassword@rabbitmq:5672/
      - AMQP_EXCHANGE=transactions-exchange
      - AMQP_QUEUE=transaction-queue
      - AMQP_ROUTING_KEY=transactions-routing-key
      - AMQP_CONSUMER_TAG=transactions-consumer
      - AMQP_WORKER_POOL_SIZE=20
    depends_on:
      - db
      - rabbitmq